services:
  - type: web
    name: discord-chess-bot
    runtime: node
    region: oregon
    buildCommand: npm install
    startCommand: node index.js
    plan: free
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
